version: "3.9"
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"  # Redis Insight
    volumes:
      - ./redis-init.sh:/usr/local/bin/redis-init.sh:ro
    entrypoint: ["/usr/local/bin/redis-init.sh"]
