version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-vector
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis-init:/docker-entrypoint-initdb.d

volumes:
  redis_data:
